### ISSUE TITLE
Can I get coordinates of baselines

### ISSUE THREAD

**Issue by longwall** [TobiasGruening/ARU-Net#15]
Hello,
I got output channels from few my images and it looks really cool.  
The next evident question is about further segmentation.
Is it possible to get array of X-Y  coordinates of each given baseline curve?
Ideally each word or phrase is bound by rectangle or (better) polygon - defined by its nodes coordinates.
As I see in the referenced article  baseline curve is vectorized.
Is there the code  in this project?

**Comment by TobiasGruening** [comment]
Dear longwall,

to get the vectorized curves one has to evaluate the neural network output. This is done in the paper via a clustering approach on so called super pixels, which are calculated based on the pixel-wise baseline confidences. Unfortunately, this clustering is not open source due to licensing issues with underlying libs.

Kind regards,
Tobias

**Comment by imagine5am** [comment]
You can get baseline coordinates using this [repository](https://github.com/imagine5am/ARU-Net).

**Comment by longwall** [comment]
imagine5am - thank you veru much! I'll try your fork as soon as I can. 
I've just tested one example at P2PaLa online DEMO . It looks interesting - but accuracy of line bouning looks not enough for my purposes.
Dear Tobias, just want to thank you one more time for your cool project. I'm on dev activity now for some time - but have no time enough. I managed to implement some tricks to improve accuracy of bounding polygons , even using only dhSegment functionality. Now I'm going to go to the stages of words deslanting and lines slope correction.
